config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "movies#index"
  resources :movies, only: [:index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :lists, only: [:index, :new, :create, :show, :destroy ] do
    resources :reviews, only: :create
  end

  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  # allow us to do: @bookmark.movie
  belongs_to :list

  # validates :list_id, presence: true
  # a movie can only show up once in every list
  validates :movie, uniqueness: { scope: :list_id, message: "is already in the list"}
  validates :comment, length: { minimum: 6 }
  validates_presence_of :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_movie, only: %i[new create]

  def new
    set_movie
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end


  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @lists = List.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-5">
  <%= @bookmark.errors.full_messages.first if @bookmark.errors.any? %>
  <%= simple_form_for [ @movie, @bookmark ] do |f| %>
    <%= f.input :comment %>
    <%= f.association :list %>
    <%= f.submit "Add movie to list", class: "btn btn-dark" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%# navbar %>
    <div class="navbar navbar-expand-sm navbar-light navbar-movie">
      <div class="container-fluid mt-2">
        <a href="/">
          <%= image_tag "movie-studio.jpg", alt: "movie logo", width: 160 %>
        </a>
      </div>

      <div class= "d-flex">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <%= link_to "Home", "/", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My Lists", lists_path, class: "nav-link" %>
              </li>
          </ul>
        </div>

        <%# <% search_form %>
        <%= simple_form_for :search, url: root_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="search[query]" id="search_query" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <main>
      <%= yield %>
      </main>
    </div>

    <div class="footer mt-3">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright fs-6">
        <p>This is made by <i class="fas fa-heart"></i> Claire Lin</p>
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover d-flex align-items-center justify-content-center mb-3">
  <h2>Save any kind of movies</h2>
</div>

<div class="container">
  <% if @lists.empty? %>
  <h3>No lists yet...</h3>
  <% else %>
  <h1 class="mt-4 mb-2">My Lists</h1>
    <div class="row">
      <% @lists.each do |list| %>
        <div class="co-12 col-sm-6 col-md-4 mb-3">
          <%# list cards %>
          <%= link_to list_path(list), class:"text-decoration-none" do%>
            <div class="card-category"
            data-aos="zoom-in"
            style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)),
            url(<%= list.photo.attached? ? cl_image_path(list.photo.key): asset_path('list_background.jpg') %>)">
              <%= list.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

 <%# Form for new list %>

  <div class="py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="create-list rounded p-3 shadow">
          <h3>Add new list</h3>
          <%= simple_form_for @list do |f| %>
            <%= f.input :name, placeholder: 'Drama' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: 'btn btn-gradient' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/lists/show.html.erb
<div class="cover-list d-flex align-items-center justify-content-center mb-3">
  <div class="cover-list"
  data-aos="zoom-in"
  style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)),
  url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key): asset_path('list_background.jpg') %>)">
    <h2><%= @list.name %></h2>
  </div>
</div>

<div class="container mb-5">
  <div>
    <%= link_to "Add a movie", root_path, class: "btn btn-gradient btn-sm" %>
    <%= link_to "Delete List", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" }, class: "btn btn-gradient btn-sm" %>
  </div>
  <hr>
  <%# list card %>
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
  </div>

  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%# review %>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.reviews.each do |review| %>
        <div>
          <% review.rating.round.to_i.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>

          <%= f.input :rating, as: :select, collection: (1..5),
            required: true, prompt: "What's your rating",
            input_html: { data: { controller: "star-rating" } }
            %>
          <%= f.submit "Submit review", class:"btn btn-gradient" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class= "movies-grid container min-vh-100 mt-3">
  <% @movies.each do |movie| %>
  <div class="card movie-card grid-item">
    <img src="<%= movie.poster_url %>" class="card-img-top rounded" alt="<%= movie.title %>">
    <div class="card-body d-flex flex-column">
      <h5 class="card-title"><%= movie.title %></h5>
      <p class="card-text "><%= movie.overview.first(50)+"...." %></p>
      <%= link_to 'Read All',  movie_path(movie), class: "btn btn-gradient btn-sm" %>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="container movie-page-card">
  <img src="<%= @movie.poster_url %>" alt="<%= @movie.title %>" class="movie-poster">
  <div class="movie-elements">
    <img src="<%= @movie.backdrop_path %>" alt="<%= @movie.title %>">
    <div class="movie-infos mt-4">
      <h3><%= @movie.title %></h3>
      <p><%= @movie.release_date %></p>
      <p><%= @movie.overview %></p>
      <p>Rating: <%= "⭐️" * @movie.rating %></p>
      <div class="dropdown movieBtn">
      <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Add to a list
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% @lists.each do |list| %>
          <%= link_to list.name, new_movie_bookmark_path(@movie),
          class: "dropdown-item"
          %>
        <% end %>
        <hr>
        <%= link_to "+ Add new list", "/lists/#new-list", class: "dd-new-list-btn"%>
      </ul>
    </div>
  </div>
</div>